# -*- coding: utf-8 -*-
"""wtech.yapayzekaodevi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-L3PS5N7e7N9GK-Iu84x_eIzs4_y3_Q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("1000_companies_listandrating.csv")

df

df.head()

df.dtypes

df.columns

df.isnull().sum()

sns.heatmap(df.isnull(),cbar=False)

from sklearn.datasets import load_iris

iris = load_iris()

iris

x = iris.data
y = iris.target

y

x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

model = Sequential()
model.add(Dense(units=8,input_dim = 4,activation="relu"))
model.add(Dense(units=10,activation="relu"))
model.add(Dense(units=3,activation="softmax"))

model.summary()

model.compile(loss="sparse_categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

model = Sequential()
model.add(Dense(units=8,input_dim = 4,activation="relu"))
model.add(Dense(units=10,activation="relu"))
model.add(Dense(units=3,activation="softmax"))

model.compile(loss="sparse_categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

from tensorflow.python.keras.models import load_model

